DROP TABLE IF EXISTS channelsub;

DROP TABLE IF EXISTS channel;

DROP TABLE IF EXISTS postread;

DROP TABLE IF EXISTS post;

DROP TABLE IF EXISTS board;

DROP TABLE IF EXISTS memberstorage;

DROP TABLE IF EXISTS gamemember;

DROP TABLE IF EXISTS game;

DROP TABLE IF EXISTS userstorage;

DROP TABLE IF EXISTS usersession;

DROP TABLE IF EXISTS user;
